#!/usr/bin/env -S sh -eu

dhclient-script "$@"

if grep -q '.dhclient-new' "$(which dhclient-script)"; then
	cat /etc/resolv.conf.dhclient-new* > '/etc/resolv.conf' && \
		rm -f /etc/resolv.conf.dhclient-new*
	chmod o+r '/etc/resolv.conf'
fi
