#!/bin/bash

set -euo pipefail
shopt -s inherit_errexit

AVAIL_FEATURES=(dhcp dhcp6 macvlan)

OPT_OVERWRITE=no
OPT_PARENT_IF=
OPT_NOW=no
OPT_MAC=
OPT_HELP=

PARGS=()
while [[ $# -gt 0 ]]; do
	if [[ $1 == '-'* ]]; then
		case "$1" in
			--parent_if)
				OPT_PARENT_IF="$2"
				shift 2
			;;
			
			--mac)
				OPT_MAC="$2"
				shift 2
			;;
			
			--overwrite)
				OPT_OVERWRITE=yes
				shift 1
			;;
			
			--now)
				OPT_NOW=yes
				shift 1
			;;
			
			--help)
				OPT_HELP=yes
				shift 1
			;;
			
			*)
				>&2 echo "Invalid option."
				exit 1
			;;
		esac
	else
		PARGS+=($1)
		shift 1
	fi
done

if [[ "$OPT_HELP" == "yes" ]]; then
	
	cat <<-EOF
		Switches:
		  --now                        Start, restart or stop services now.
		  --overwrite                  Overwrite config with new config if applicable to feature.
		  --parent_if <interface>      Parent interface for macvlan.
		  --mac <mac address>          MAC address of macvlan interface.
			
		Commands:
		  --now                        Start, restart or stop services now.
		  --overwrite                  Overwrite config with new config if applicable to feature.
		  --parent_if <interface>      Parent interface for macvlan.
		  --mac <mac address>          MAC address of macvlan interface.
		
		Commands:
		  enable <namespace> [<list of features>]
		  disable <namespace> [<list of features>]
		  add-service <service> <namespace>
		  remove-service <service>
		  status [<namespace>]
		  start|restart|stop <namespace>
			
		Features:
		  dhcp                         Start a dhcp client inside namespace.
		  dhcp6                        Start a dhcpv6 client inside namespace.
		  macvlan                      Create a macvlan interface inside namespace.
	EOF
	
	exit
	
fi

FLAGS=()
if [[ "$OPT_NOW" == yes ]]; then FLAGS+=(--now); fi

read_service()
{
	SERVICE="$1"
	
	[[ ! -z "$SERVICE" ]] || \
		{
			>&2 echo "No service given."
			exit 1
		}
	
	if [[ $SERVICE != *.service ]]; then
		SERVICE="${SERVICE}.service"
	fi

	[[ ! -z $(systemctl list-unit-files --full --all --no-legend --type service "$SERVICE") ]] || \
		{
			>&2 echo "Service \`$SERVICE\` not found."
			return 1
		}
}

feature_is_valid()
{
	for f in ${AVAIL_FEATURES[@]}; do [[ "$f" == "$1" ]] && return 0; done
	return 1
}

add_features()
{
	local NS=$1
	shift 1
	
	for feature in "$@"; do
		feature_is_valid "$feature" || 
			{
				>&2 echo "Invalid feature \`$feature\`."
				return 1
			}
	done
	
	for feature in "$@"; do
		case "$feature" in
			macvlan)
				if [[ "$OPT_OVERWRITE" == yes || ! -f "/etc/netns-helper/ns/$NS-macvlan.conf" ]]; then
					[[ ! -z "$OPT_PARENT_IF" ]] || \
						{
							>&2 echo "The parent interface of the macvlan interface must be specified with option \`--parent_if <interface>\`."
							exit 1
						}
						
					[[ -f "/etc/netns-helper/ns/$NS-macvlan.conf" ]] && \
						echo "Configuration file \`/etc/netns-helper/ns/$NS-macvlan.conf\` overwritten."
						
					umask 022
					cat > "/etc/netns-helper/ns/$NS-macvlan.conf" <<- EOF
						PARENT_IF="$OPT_PARENT_IF"
						MAC=$OPT_MAC
					EOF
				else
					[[ -f "/etc/netns-helper/ns/$NS-macvlan.conf" ]] && \
						echo "Configuration file \`/etc/netns-helper/ns/$NS-macvlan.conf\` already exists and will not be overwritten."
				fi
			;;
		esac
		
		systemctl enable netns-helper-$feature@$NS.service "${FLAGS[@]}"
	done
}

case ${PARGS[0]:-} in
	add-service)
		read_service "${PARGS[1]:-}"
		NS=${PARGS[2]:-}
		
		[[ ! -z "$NS" ]] || \
			{
				>&2 echo "No namespace given."
				exit 1
			}
		
		umask 022
		
		mkdir -p "/etc/systemd/system/$SERVICE.d"
		cat > "/etc/systemd/system/$SERVICE.d/netns-helper.conf" <<- EOF
			[Unit]
			After=netns-helper@${NS}.target
			Requisite=netns-helper@${NS}.target
			PartOf=netns-helper@${NS}.target
			JoinsNamespaceOf=netns-helper@${NS}.service
			ConditionPathExists=/var/run/netns/${NS}

			[Service]
			PrivateNetwork=true

			BindPaths=-/etc/netns/${NS}/resolv.conf:/etc/resolv.conf
			BindPaths=-/etc/netns/${NS}/nsswitch.conf:/etc/nsswitch.conf
		EOF
		
		systemctl daemon-reload
		
		if [[ "$OPT_NOW" == yes ]]; then
			systemctl restart $SERVICE
		fi
		
		echo "Service \`$SERVICE\` added to network namespace \`$NS\`."
	;;
	
	remove-service)
		read_service "${PARGS[1]}"
		
		rm -f "/etc/systemd/system/$SERVICE.d/netns-helper.conf"
		
		systemctl daemon-reload
		
		if [[ "$OPT_NOW" == yes ]]; then
			systemctl restart $SERVICE
		fi
		
		echo "Service \`$SERVICE\` removed from network namespace."
	;;
	
	enable)
		NS=${PARGS[1]:-}
		
		[[ ! -z "$NS" ]] || \
			{
				>&2 echo "No namespace given."
				exit 1
			}
		
		systemctl enable netns-helper@$NS.service
		
		add_features $NS "${PARGS[@]:2}"
		
		systemctl enable netns-helper@$NS.target "${FLAGS[@]}"
	;;
	
	disable)
		NS=${PARGS[1]:-}
		
		[[ ! -z "$NS" ]] || \
			{
				>&2 echo "No namespace given."
				exit 1
			}
			
		features=(${PARGS[@]:2})
		
		if [[ ${#features[@]} == 0 ]]; then
			systemctl disable netns-helper@$NS.target "${FLAGS[@]}"
		else
			for feature in ${features[@]}; do
				systemctl disable netns-helper-$feature@$NS.service "${FLAGS[@]}"
			done
		fi
		
		systemctl disable netns-helper@$NS.target "${FLAGS[@]}"
	;;
	
	status)
		NS=${PARGS[1]:-}
		
		if [[ -z "$NS" ]]; then
			namespaces=$(systemctl list-units --type target "netns-helper@*.target" --all --no-legend --full | sed -r 's/^(\s*)netns-helper@(\S+)\.target(.*)/netns-helper@\2.target/')
			for n in ${namespaces//\\n/}; do
				systemctl list-dependencies "$n"
			done
		else
			systemctl list-dependencies "netns-helper@${NS}.target"
		fi
	;;
	
	start)
		NS=${PARGS[1]:-}
		
		systemctl start netns-helper@$NS.target
	;;
	
	stop)
		NS=${PARGS[1]:-}
		
		systemctl stop netns-helper@$NS.target
	;;
	
	restart)
		NS=${PARGS[1]:-}
		
		systemctl restart netns-helper@$NS.target
	;;
	
	list)
		systemctl list-units --all --type target "netns-helper*"
	;;
	
	*)
		>&2 echo "Wrong command."
		exit 1
	;;
esac
